Fixed examples and added else

diff --git a/src/helmc b/src/helmc
--- a/src/helmc
+++ b/src/helmc
@@ -28,6 +28,17 @@ function exists {
   return $?
 }
 
+CLEANUP=()
+
+function cleanup {
+  if [[ ${#CLEANUP[@]} > 0 ]]
+  then
+    rm -r ${CLEANUP[@]}
+  fi
+}
+
+trap cleanup EXIT
+
 if test -z "$CC" 
 then
 
@@ -76,6 +87,8 @@ function compile {
     exit 1
   fi
   
+  CLEANUP+=( "$CTMP" )
+
   $HELMC1 < "$1" > "$CTMP"
   
   if [[ -z $noBuild ]]
@@ -85,10 +98,9 @@ function compile {
 
     $CC -o "$OTMP" -c "$CTMP" -Wno-parentheses-equality -g
 
-    OBJS+=( $OTMP )
+    OBJS+=( "$OTMP" )
 
-    rm "$CTMP"
-
+    CLEANUP+=( "$OTMP" )
   fi
   
 }
@@ -102,14 +114,7 @@ function link {
 
   fi
 
-  $CC -o "$outName" "$HELMRT" $OBJS
-
-  for obj in "${OBJS[@]}"
-  do 
-    
-    rm "$obj"
-
-  done
+  $CC -o "$outName" "$HELMRT" ${OBJS[@]}
 
 }
 
